# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane test

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
      setup_ci
      match(type: "appstore", readonly: true, git_basic_authorization: 'eW91cl9naXRodWJfdXNlcm5hbWU6Z2hwX0piM0FVYjJTQWtxeHJvT0xXRksxdTlvbTd1WG42aDJYRzVFSQ==')  # see code signing guide for more information
      build_app(scheme: "Runner",
                  workspace: "Runner.xcworkspace",
                  silent: false,
                  clean: true)
  end
end
