name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo current directory
        run: |
          pwd
      - name: Change directory
        run: ls
      - name: Build iOS
        run: 
          fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
