name: build-ios-app
on:
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS
        working-directory: ios/fastlane/
        run: 
          fastlane beta --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
