name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS
        working-directory: ios/fastlane/
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - name: Install dependencies
        run: |
          gem install bundler
          cd android && bundle install
          cd ../ios && bundle install
      - name: Build and test
        run: |
          flutter build ios --release --no-codesign
          cd ios 
          bundle exec fastlane beta
      - name: Log
        run: cat /Users/runner/Library/Logs/gym/Runner-Runner.log
        if: always()
