name: build-ios-app
on:
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS
        working-directory: ios/fastlane/
        run: 
          fastlane beta
      - run: cat /Users/runner/work/ci_test/ci_test/ios/fastlane/README.md # Or log file include on outputs
        if: always()
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
