
name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS
        working-directory: ios/fastlane/
        run: 
          fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - name: Log
        run: cat /Users/runner/Library/Logs/gym/Runner-Runner.log
