name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build iOS
        working-directory: ios/fastlane/
        run: 
          fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - name: Log
        run: cat /Users/runner/work/ci_test/ci_test/ios/fastlane/README.md # Or log file include on outputs
        if: always()
      - name: Clean up keychain and provisioning profile
        run: |
         security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
         rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision

